services:
  redis-server:
      image: redis
      container_name: redis-microservice-server
      ports: 
        - "6379:6379"
      volumes: 
        - ./redis-service/config/redis.conf:/redis.conf
        # - ./redis-data:/redis.conf
      command: [ "redis-server", "/redis.conf" ]
      # networks: 
      #   - redis-net
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_CLIENT_DB=${CLIENT_DB_NAME}
      - POSTGRES_ADMIN_DB=${ADMIN_DB_NAME}
    container_name: mks-service-postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # networks: 
    #   - redis-net
  mks-consumer:
    build: 
      context: ./mks-consumer
      dockerfile: ./Dockerfile
    image: rafaelnwitter/mks-consumer-app:latest
    environment: 
      - DB_TYPE=${DB_TYPE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_CLIENT_DB=${CLIENT_DB_NAME}
      - POSTGRES_SYNC=false
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_PORT=${APP_PORT}
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    ports: 
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: mks-consumer-app
    depends_on: 
      - db
      # - redis-server
    volumes: 
      - ./mks-consumer:/app
      - /app/node_modules
    # networks: 
    #   - redis-net
  mks-api:
    build:
      context: ./mks-api
      dockerfile: ./Dockerfile
    image: rafaelnwitter/mks-api:latest
    volumes: 
        - ./mks-api:/app
        - /app/node_modules
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on: 
      - db
      # - redis-server


# networks: 
#   redis-net: null
volumes:
  pgdata:
  pgadmin-data:
  redis-data:
